import { PeerConnection, DataChannel } from "node-datachannel";
import { EventEmitter } from "events";
import { SignalingClient } from "../signaling/client";
import { SignalPayload } from "../signaling/types";
import { resolveIceServers } from "./config";

export interface WebRTCPeerOptions {
  name: string;
  isInitiator: boolean;
  roomId: string;
  signalingClient: SignalingClient;
  customIceServers?: string[];
}

export class WebRTCPeer extends EventEmitter {
  private pc: PeerConnection | null = null;
  private dc: DataChannel | null = null;
  private isRemoteDescriptionSet = false;
  private pendingCandidates: Array<{ candidate: string; mid?: string }> = [];

  constructor(private options: WebRTCPeerOptions) {
    super();
  }

  public async start(): Promise<void> {
    const { name, isInitiator, roomId, signalingClient, customIceServers } = this.options;
    const iceServers = resolveIceServers(customIceServers);

    this.pc = new PeerConnection(name, {
      iceServers,
    });

    // Handle local descriptions (Offer/Answer) generated by node-datachannel
    this.pc.onLocalDescription((sdp: string, type: string) => {
      signalingClient.sendSignal(roomId, {
        type: type as "offer" | "answer",
        sdp,
      });
    });

    // Handle local ICE candidates gathered
    this.pc.onLocalCandidate((candidate: string, mid: string) => {
      signalingClient.sendSignal(roomId, {
        type: "candidate",
        candidate,
        sdpMid: mid,
      });
    });

    // Connection state logging
    this.pc.onStateChange((state: string) => {
      this.emit("stateChange", state);
      if (state === "failed") {
        this.emit("error", new Error("WebRTC PeerConnection failed."));
      }
    });

    // Handle incoming signals from the signaling server
    signalingClient.on("signal", (payload: SignalPayload) => {
      this.handleRemoteSignal(payload);
    });

    if (isInitiator) {
      // For initiator, wait for peer to join before creating DataChannel / generating offer
      signalingClient.on("peer-joined", () => {
        if (this.pc && !this.dc) {
          const channel = this.pc.createDataChannel("p2pcopy-datachannel");
          this.setupDataChannel(channel);
        }
      });
    } else {
      // Receiver waits for incoming DataChannel from initiator
      this.pc.onDataChannel((channel: DataChannel) => {
        this.setupDataChannel(channel);
      });
    }
  }

  private handleRemoteSignal(payload: SignalPayload): void {
    if (!this.pc) return;

    if (payload.type === "offer") {
      this.pc.setRemoteDescription(payload.sdp, "offer");
      this.isRemoteDescriptionSet = true;
      this.drainPendingCandidates();
    } else if (payload.type === "answer") {
      this.pc.setRemoteDescription(payload.sdp, "answer");
      this.isRemoteDescriptionSet = true;
      this.drainPendingCandidates();
    } else if (payload.type === "candidate") {
      if (this.isRemoteDescriptionSet) {
        this.pc.addRemoteCandidate(payload.candidate, payload.sdpMid || "0");
      } else {
        this.pendingCandidates.push({ candidate: payload.candidate, mid: payload.sdpMid });
      }
    }
  }

  private drainPendingCandidates(): void {
    if (!this.pc) return;
    while (this.pendingCandidates.length > 0) {
      const { candidate, mid } = this.pendingCandidates.shift()!;
      this.pc.addRemoteCandidate(candidate, mid || "0");
    }
  }

  private setupDataChannel(channel: DataChannel): void {
    this.dc = channel;

    channel.onOpen(() => {
      this.emit("connected", channel);
    });

    channel.onClosed(() => {
      this.emit("disconnected");
    });

    channel.onError((err: string) => {
      this.emit("error", new Error(`DataChannel error: ${err}`));
    });

    channel.onMessage((msg: string | ArrayBuffer | Buffer) => {
      const payload = typeof msg === "string" ? msg : (Buffer.isBuffer(msg) ? msg : Buffer.from(msg));
      this.emit("data", payload);
    });
  }

  public getDataChannel(): DataChannel | null {
    return this.dc;
  }

  public close(): void {
    if (this.dc) {
      this.dc.close();
      this.dc = null;
    }
    if (this.pc) {
      this.pc.close();
      this.pc = null;
    }
  }
}